//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.ReportFramework {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportFramework.IReportContract")]
    public interface IReportContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportContract/PrintReportCustomById", ReplyAction="http://tempuri.org/IReportContract/PrintReportCustomByIdResponse")]
        void PrintReportCustomById(int idReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportContract/PrintReportCustomById", ReplyAction="http://tempuri.org/IReportContract/PrintReportCustomByIdResponse")]
        System.Threading.Tasks.Task PrintReportCustomByIdAsync(int idReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportContract/ShowReportList", ReplyAction="http://tempuri.org/IReportContract/ShowReportListResponse")]
        void ShowReportList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportContract/ShowReportList", ReplyAction="http://tempuri.org/IReportContract/ShowReportListResponse")]
        System.Threading.Tasks.Task ShowReportListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportContractChannel : ReportFramework.IReportContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportContractClient : System.ServiceModel.ClientBase<ReportFramework.IReportContract>, ReportFramework.IReportContract {
        
        public ReportContractClient() {
        }
        
        public ReportContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PrintReportCustomById(int idReport) {
            base.Channel.PrintReportCustomById(idReport);
        }
        
        public System.Threading.Tasks.Task PrintReportCustomByIdAsync(int idReport) {
            return base.Channel.PrintReportCustomByIdAsync(idReport);
        }
        
        public void ShowReportList() {
            base.Channel.ShowReportList();
        }
        
        public System.Threading.Tasks.Task ShowReportListAsync() {
            return base.Channel.ShowReportListAsync();
        }
    }
}
